# frozen_string_literal: true

appraise 'rails-5.0' do
  gem 'activemodel', '~> 5.0.0'
end

appraise 'rails-5.1' do
  gem 'activemodel', '~> 5.1.0'
end

appraise 'rails-5.2' do
  gem 'activemodel', '~> 5.2.0'
end
