# Beware! This file is public by definition
default: &default
  default_team_name: 'Demo-team'
  # This settings is included only for the specs. Don't remove
  test_setting: 'test123' 
  logo:
    mentor_logo: 'logo_mentor.png'
    student_logo: 'logo_student.png'
    fallback_logo: 'logo.png'
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
