# Beware! This file is public by definition
default: &default
  default_team_name: 'Demo-team'
  # This settings is included only for the specs. Don't remove
  test_setting: 'test123' 
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
