apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    worker: "no"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: web
        track: stable
    spec:
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 4 }}
      containers:
        - name: {{ .Release.Name }}
          imagePullPolicy: Always
          image: {{ .Values.image }}
          resources:
            limits:
              memory: "1.5Gi"
            requests:
              memory: "768Mi"
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
          - secretRef:
              name: {{ .Values.secretName }} 
          - containerPort: 3000
            protocol: TCP
          # The readiness probe is triggered after the startup probe. We
          # already found that the pod was ready, hence 1 initial delay. After
          # that it will poll every 30 seconds, and if it fails twice, the pod
          # is killed.
          readinessProbe:
            httpGet:
              path: /status
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          # The startup probe is triggered when starting up the application. It
          # waits for 20 seconds before it starts polling. The polling will
          # happen every 5 seconds, and will continue for 60 tries. That is, if
          # the pod is not ready within 60*5+20 seconds, it wont be started.
          startupProbe:
            httpGet:
              path: /status
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 4
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 60

