apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-questionnaires-worker
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-questionnaires-worker
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 150 # equals 1,5 x requests.memory = 1152Mi
          