apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: svc-questionnaires-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-questionnaires
      tier: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: svc-questionnaires
        track: stable
        tier: worker
    spec:
      imagePullSecrets:
        - name: {{ .Values.gitlabAuthSecretName }}
        - name: {{ .Values.dockerAuthSecretName }}
      containers:
        - name: svc-questionnaires
          imagePullPolicy: Always
          image: docker.io/researchableuser/sdv-svc-questionnaires:{{ .Values.tag }}
          resources:
            limits:
              memory: "1.5Gi"
            requests:
              memory: "768Mi"
          command: ['bundle', 'exec', 'rake', 'jobs:work']
          env:
          - name: RAILS_ENV
            value: production
          - name: RACK_ENV
            value: production
          - name: NODE_ENV
            value: production
          - name: APPSIGNAL_ACTIVE
            value: "true"
          - name: REVISION
            value: {{ .Values.commitSha }}
          - name: APPSIGNAL_APP_ENV
            value: {{ .Values.appsignalAppEnv }}
          - name: PAPERTRAIL_PROGRAM
            value: djq
          - name: APPSIGNAL_PUSH_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: APPSIGNAL_PUSH_API_KEY
          - name: PUSH_SUBSCRIPTION_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PUSH_SUBSCRIPTION_URL
          - name: BASE_PLATFORM_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: BASE_PLATFORM_URL
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: DATABASE_URL
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: SECRET_KEY_BASE
          - name: HOST_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: HOST_URL
          - name: HOST_DOMAIN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: HOST_URL
          - name: INFO_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: INFO_EMAIL
          - name: FEEDBACK_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: FEEDBACK_EMAIL
          - name: MESSAGEBIRD_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MESSAGEBIRD_ACCESS_KEY
          - name: MESSAGEBIRD_SEND_FROM
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MESSAGEBIRD_SEND_FROM
          - name: PERSON_SALT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PERSON_SALT
          - name: STOP_SUBSCRIPTION_SALT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: STOP_SUBSCRIPTION_SALT
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: ADMIN_USERNAME
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: ADMIN_PASSWORD
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MAILGUN_API_KEY
          - name: MAILGUN_DOMAIN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MAILGUN_DOMAIN
          - name: FROM_EMAIL_ADDRESS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: FROM_EMAIL_ADDRESS
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: AUTH0_CLIENT_ID
          - name: AUTH0_DOMAIN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: AUTH0_DOMAIN
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: AUTH0_CLIENT_SECRET
          - name: AUTH0_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: AUTH0_REDIRECT_URL
          - name: AUTH0_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: AUTH0_AUDIENCE
          - name: AUTH0_SIGNING_CERTIFICATE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: AUTH0_SIGNING_CERTIFICATE
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: REDIS_URL
          - name: TEST_PHONE_NUMBERS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: TEST_PHONE_NUMBERS
          - name: SNITCH_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: SNITCH_KEY
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: API_KEY
          - name: API_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: API_SECRET
          - name: IP_HASH_SALT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: IP_HASH_SALT
          - name: INFO_SITE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: INFO_SITE_URL
          - name: TOKEN_SIGNATURE_ALGORITHM
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: TOKEN_SIGNATURE_ALGORITHM
          - name: PAPERTRAIL_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PAPERTRAIL_PORT
          - name: PAPERTRAIL_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PAPERTRAIL_HOST
          - name: RAILS_SERVE_STATIC_FILES
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: RAILS_SERVE_STATIC_FILES
          - name: MAILGUN_API_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MAILGUN_API_HOST
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MONGODB_URI
          - name: PROJECT_START_DATE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PROJECT_START_DATE
          - name: PROJECT_END_DATE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PROJECT_END_DATE
          - name: PROJECT_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: PROJECT_NAME
          - name: SITE_LOCATION
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: SITE_LOCATION
          - name: WEB_CONCURRENCY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: WEB_CONCURRENCY
          - name: RAILS_MAX_THREADS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: RAILS_MAX_THREADS
