# load docker image & start docker engine
image: tmaier/docker-compose:latest
services:
  - docker:dind

# define pipline stages
stages:
  - build
  - deploy

variables:
  KUBE_NAMESPACE: sdvmvp-questionaires
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_REPO: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  DEPLOY_TAG: $CI_COMMIT_SHA
  PROJECT_NAME: sport-data-valley

build_web_job:
  stage:
    build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "PROJECT_NAME=${PROJECT_NAME}" > .env.local
    - printenv
    - docker build . -t ${IMAGE_REPO}:${CI_COMMIT_SHA}

deploy_web_job:
  stage:
    deploy
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: develop
    url: https://sdvmvp.researchable.nl
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "Deploying to namespace ${KUBE_NAMESPACE}"
    - kubectl version
    - cd manifests/
    - sed -i s/__CI_COMMIT_REF_NAME__/${__CI_COMMIT_REF_NAME__}/
    - cat deployment.yml
