# load docker image & start docker engine
image: tmaier/docker-compose:latest
services:
  - docker:dind

# define pipline stages
stages:
  - build
  - deploy

variables:
  KUBE_NAMESPACE: sdvmvp-questionaires
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_REPO: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  DEPLOY_TAG: $CI_COMMIT_SHA
  PROJECT_NAME: sport-data-valley

build_web_job:
  stage:
    build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "PROJECT_NAME=${PROJECT_NAMEs}" > .env.local
    - export CI_COMMIT_REF_NAME_UP=`echo $CI_COMMIT_REF_NAME | awk '{ print toupper($0) }' | sed 's/-/_/g'`
    - env | grep K8S_SECRET_
    - env | grep K8S_SECRET_ | sed "s/^K8S_SECRET_\(.*\)$/\1/g" | sed "s/^${CI_COMMIT_REF_NAME_UP}_\(.*\)$/\1/g" > .env.local
    - cat .env.local
    - docker build . -t ${IMAGE_REPO}:${CI_COMMIT_SHA}


deploy_web_job:
  stage:
    deploy
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: develop
    url: https://sdvmvp.researchable.nl
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "Deploying to namespace ${KUBE_NAMESPACE}"
    - kubectl version
    - cd manifests/
    - sed -i s/__CI_COMMIT_REF_NAME__/${__CI_COMMIT_REF_NAME__}/
    - cat deployment.yml
    - touch .env
    - export CI_COMMIT_REF_NAME_UP=`echo $CI_COMMIT_REF_NAME | awk '{ print toupper($0) }'`
    # delete old integrations URL
    - sed -i 's/^INTEGRATIONS_URL=.*//' .env
    # insert new integrations url and internal integrations url
    - eval echo "INTEGRATIONS_URL=\$${CI_COMMIT_REF_NAME_UP}_INTEGRATIONS_URL" >> .env
    - eval echo "INTEGRATIONS_URL_INTERNAL=\$${CI_COMMIT_REF_NAME_UP}_INTEGRATIONS_URL_INTERNAL" >> .env
    # replace HOST_URL with production value
    - eval "sed -i 's|^HOST_URL=.*|HOST_URL=${K8S_SECRET_DEVELOP_HOST_URL}|' .env"
    # override hostname to which SessionToken is available
    - eval "sed -i 's|SESSION_COOKIE_HOSTNAME=.*|SESSION_COOKIE_HOSTNAME=${K8S_SECRET_DEVELOP_COOKIE_DOMAIN}|' .env"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
