include:
  - project: researchable/general/templates/gitlab/base
    ref: master
    file: docker/build.yml

# include:
    # Adds the 'semantic releases' to the release stage
  # - project: 'researchable/general/templates/gitlab/semantic-release'
  #   ref: master
  #   file: 'semantic_release.yml'
  # Adds the 'docker deploy' based on the versions in the semantic relase to the deploy stage
  # - project: 'researchable/general/templates/gitlab/docker-deploy'
  #   ref: master
  #   file: 'docker_deploy.yml'

# define pipline stages
stages:
  - build
  # - test
  - release

variables:
  KUBE_NAMESPACE: sdv-mvp-$CI_COMMIT_REF_NAME
  PROJECT_NAME: sport-data-valley
  CI: 'true'

  # docker build variables
  IMAGE_NAME: researchableuser/sdv-svc-questionnaires
  IMAGE_TAGS: $CI_COMMIT_SHA,latest
  REGISTRY_USERNAME: $DOCKER_HUB_USERNAME
  REGISTRY_PASSWORD: $DOCKER_HUB_PASSWORD
  REGISTRY_HOST: docker.io

build_web_job:
  extends: .docker_build_job
  variables:
    BUILD_ARG_PROJECT_NAME: $PROJECT_NAME
    BUILD_ARG_RAILS_ENV: production
    BUILD_ARG_NODE_ENV: production
  only:
    refs:
      - master
      - production
      - develop
