version: '2'
services:
  db:
    image: 'postgres'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: "redis:alpine"
    networks:
      - backend
  mongo:
    image: "mongo:latest"
    networks:
      - backend
  web:
    build: .
    entrypoint: ["/app/lib/docker-entrypoint.sh"]
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    volumes:
      - .:/app
    ports:
      - "80:3000"
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - redis
      - mongo
networks:
  frontend:
  backend:

