version: '3.7'
services:
  db:
    image: postgres:10.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:delegated
  redis:
    image: "redis:5.0.6-alpine"
    command: redis-server --requirepass redispassword
    volumes:
      - ./tmp/redis:/data:delegated
  mongo:
    image: mongo:4
    volumes:
      - ./tmp/mongo:/data/db:delegated
  webpack:
    image: vsv
    entrypoint: []
    command: ["bundle","exec","bin/webpack-dev-server"]
    restart: on-failure
    volumes:
      - .:/app:delegated
      - node_modules_volume:/app/node_modules
      - gems_volume:/usr/local/bundle/ruby/2.6.0
      - /app/tmp
    ports:
      - "8080:3036"
    depends_on:
      - web
    links:
      - web
  web:
    image: vsv
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        precompileassets: 'not'
    entrypoint: ["/app/lib/docker-entrypoint.sh"]
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - RESET_DB_ON_FAIL=true
      - RUNNING_AS_SERVICE=true # Because we don't run a delayed job server in the docker container
    volumes:
      - .:/app:delegated
      - node_modules_volume:/app/node_modules
      - gems_volume:/usr/local/bundle/ruby/2.6.0
      - /app/tmp
    ports:
      - "3002:3000"
    depends_on:
      - db
      - redis
      - mongo
volumes:
  node_modules_volume:
  gems_volume:
