apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker-budget
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}
      tier: worker
