# frozen_string_literal: true

db_title = '' # Shown to users as a big text, but cannot be localized, so often left empty.

db_name1 = 'usc_chan' # Internal name to identify this questionnaire by. Should be unique.
dagboek1 = Questionnaire.find_by(key: File.basename(__FILE__)[0...-3])
dagboek1 ||= Questionnaire.new(key: File.basename(__FILE__)[0...-3])
dagboek1.name = db_name1
dagboek_content = [
  {
    section_start: '',
    type: :raw,
    content: '<p class="flow-text">EMA Questions</p>'
  }, {
    id: :v1,
    required: true,
    type: :radio,
    title: 'Is this your first questionnaire of the day?',
    show_otherwise: false,
    options: [
      { title: 'Yes', shows_questions: %i[v2 v3 v4 v5 v6] },
      { title: 'No', shows_questions: %i[v17] }
    ],
  }, {
    id: :v2,
    hidden: true,
    required: true,
    type: :time,
    title: 'What time did you go to bed?',
    hours_from: 0,
    hours_to: 24,
    hours_step: 1,
    hours_label: 'Hours',
    minutes_label: 'Minutes',
    am_pm: true,
  }, {
    id: :v3,
    hidden: true,
    required: true,
    type: :time,
    title: 'What time did you wake up?',
    hours_from: 0,
    hours_to: 24,
    hours_step: 1,
    hours_label: 'Hours',
    minutes_label: 'Minutes',
    am_pm: true,
  }, {
    id: :v4,
    hidden: true,
    required: true,
    type: :range,
    title: 'Right now, how well rested do you feel?',
    labels: ['Not at all rested', 'Extremely rested'], # TODO: say we can do sliders without initial thumb
  }, {
    id: :v5,
    hidden: true,
    required: true,
    type: :range,
    title: 'How disrupted was your sleep last night?',
    labels: ['Not at all disrupted', 'Extremely disrupted'],
  }, {
    id: :v6,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: 'What activities do you plan to do today? <em>(select all that apply)</em>',
    options: [
      { title: 'Work/school', shows_questions: %i[v7] },
      { title: 'Travel/commute', shows_questions: %i[v8] },
      { title: 'Rest/relax', shows_questions: %i[v9] },
      { title: 'Socialize', shows_questions: %i[v10] },
      { title: 'Care for myself', shows_questions: %i[v11] },
      { title: 'Care for others', shows_questions: %i[v12] },
      { title: 'Household/errands', shows_questions: %i[v13] },
      { title: 'Fun/leisure - quiet', shows_questions: %i[v14] },
      { title: 'Fun/leisure - active', shows_questions: %i[v15] },
      { title: 'Manage my health', shows_questions: %i[v16] },
    ],
  }, {
    id: :v7,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Work/school',
    options: ['Work', 'Volunteer', 'Attend class', 'Study', 'Other work/school'],
  }, {
    id: :v8,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Travel/commute',
    options: ['Drive', 'Passenger (in car, train, bus, etc.)', 'Bike/scooter/walk', 'Other travel'],
  }, {
    id: :v9,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Rest/relax',
    options: ['Sleep/nap', 'Meditation/mindfulness', 'Yoga/tai chi', 'Other restful/rejuvenating activity'],
  }, {
    id: :v10,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Socialize',
    options: ['Socialize at home', 'Socialize online', 'Socialize away from home', 'Other social activity'],
  }, {
    id: :v11,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Care for myself',
    options: ['Eat a meal', 'Exercise', 'Hygiene/grooming', 'Other self-care'],
  }, {
    id: :v12,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Care for others',
    options: ['Caring for children', 'Caring for other family', 'Caring for pets', 'Other'],
  }, {
    id: :v13,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Household/errands',
    options: ['Cook/meal preparation', 'Clean/housework', 'Pay bills/finances', 'Shop/run errands', 'Other household'],
  }, {
    id: :v14,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Fun/leisure - quiet',
    options: ['TV/streaming/music', 'Social media', 'Reading', 'Other quiet leisure'],
  }, {
    id: :v15,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Fun/leisure - active',
    options: ['Hobbies', 'Sports/outdoors', 'Video games', 'Other active leisure'],
  }, {
    id: :v16,
    hidden: true,
    required: true,
    type: :checkbox,
    show_otherwise: false,
    title: 'Manage my health',
    options: ['Managing medications/devices', 'Healthcare errand/paperwork', 'Health appointment', 'Other health activity'],
  }, {
    id: :v17,
    hidden: true,
    required: true,
    type: :radio,
    show_otherwise: false,
    title: 'Is this your last questionnaire of the day?',
    options: [
      { title: 'Yes', shows_questions: %i[v18h v18 v19 v20 v21 v22 v23 v24 v25 v26 v27 v28] },
      { title: 'No' }
    ],
  }, {
    id: :v18h,
    type: :raw,
    hidden: true,
    content: '<p class="flow-text">How well were you able to do the following activities today?</p>'
  }, {
    id: :v18,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Work', shows_questions: %i[v18a] }],
  }, {
    id: :v18a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v19,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Travel/commute', shows_questions: %i[v19a] }],
  }, {
    id: :v19a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v20,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Rest/relax', shows_questions: %i[v20a] }],
  }, {
    id: :v20a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v21,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Socialize', shows_questions: %i[v21a] }],
  }, {
    id: :v21a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v22,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Care for myself', shows_questions: %i[v22a] }],
  }, {
    id: :v22a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v23,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Care for others', shows_questions: %i[v23a] }],
  }, {
    id: :v23a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v24,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Household/errands', shows_questions: %i[v24a] }],
  }, {
    id: :v24a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v25,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Fun/leisure - quiet', shows_questions: %i[v25a] }],
  }, {
    id: :v25a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v26,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Fun/leisure - active', shows_questions: %i[v26a] }],
  }, {
    id: :v26a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v27,
    hidden: true,
    required: false,
    type: :checkbox,
    show_otherwise: false,
    title: '',
    options: [{ title: 'Manage my health', shows_questions: %i[v27a] }],
  }, {
    id: :v27a,
    hidden: true,
    required: true,
    type: :range,
    title: '',
    labels: ['Unable to do at all', 'Extremely well'],
  }, {
    id: :v28,
    hidden: true,
    required: true,
    type: :radio,
    show_otherwise: true,
    title: 'Did diabetes get in the way of doing any of these activities today?',
    options: [
      'No',
      'Yes, I was feeling unwell',
      'Yes, self-management tasks interfered',
    ],
    otherwise_label: 'Yes, for another reason',
    otherwise_placeholder: 'Please specify',
  }, {
    id: :v29, # TODO: maybe add a separator here
    required: true,
    type: :range,
    title: 'Right now, how do you feel <strong>physically</strong>?',
    labels: ['Extremely bad', 'Extremely good'],
  }, {
    id: :v30,
    required: true,
    type: :range,
    title: 'Right now, how do you feel <strong>mentally and emotionally</strong>?',
    labels: ['Extremely bad', 'Extremely good'],
  }, {
    id: :v31,
    required: true,
    type: :range,
    title: 'Right now, how <strong>confident</strong> do you feel about tackling your day?',
    labels: ['Not at all confident', 'Very confident'],
  }, {
    id: :v32,
    required: true,
    type: :range,
    title: 'Right now, how <strong>stressed</strong> are you?',
    labels: ['Not at all stressed', 'Extremely stressed'],
  }, {
    id: :v33,
    required: true,
    type: :range,
    title: 'Right now, how <strong>bothered</strong> are you by your diabetes or its management?',
    labels: ['Not at all bothered', 'Extremely bothered'],
  }, {
    id: :v34,
    required: true,
    type: :range,
    title: 'Right now, how <strong>tired</strong> do you feel?',
    labels: ['Not at all tired', 'Extremely tired'],
  }, {
    id: :v35,
    required: true,
    type: :range,
    title: 'Right now, how <strong>aware</strong> are you of your glucose or other physical symptoms?',
    labels: ['Completely unaware', 'Completely aware'],
  }, {
    id: :v36,
    required: true,
    type: :range,
    title: 'Right now, is your <strong>eating pattern</strong> affecting how you feel?',
    labels: ['Yes, very negatively', 'Neutral', 'Yes, very positively'],
    min: -50,
    max: 50,
    value: 0,
  }, {
    id: :v37,
    required: true,
    type: :range,
    title: 'Since the last survey, have you been following your usual <strong>routine</strong>?',
    labels: ['Not at all', 'Completely'],
  }, {
    id: :v38,
    required: true,
    type: :range,
    title: 'Since the last survey, how <strong>physically active</strong> have you been?',
    labels: ['Not at all active', 'Extremely active'],
  }
]
dagboek1.content = { questions: dagboek_content, scores: [] }
dagboek1.title = db_title
dagboek1.save!
