# frozen_string_literal: true

title = 'Lima'

name = 'KCT Lima'
questionnaire = Questionnaire.find_by(name: name)
questionnaire ||= Questionnaire.new(name: name)
questionnaire.key = File.basename(__FILE__)[0...-3]

def create_question(id, title, section_end)
  res = {
    id: id,
    type: :likert,
    title: title,
    show_otherwise: false,
    options: %w[HO O N E HE]
  }
  res[:section_end] = true if section_end
  res
end

content = [
  {
    type: :raw,
    content: '
    <p class="flow-text section-explanation">
      Deze vragenlijst bevat 240 uitspraken. Lees elke uitspraak zorgvuldig. Klik vervolgens aan welke
      uitspraak jouw mening het beste weergeeft. Let er op dat je geen uitspraken overslaat.
    </p>
    <ul class="collection">
      <li class="collection-item">Klik <strong>HO</strong> aan als je het helemaal oneens bent met de uitspraak, of als je de uitspraak absoluut onwaar vindt.</li>
      <li class="collection-item">Klik <strong>O</strong> aan als je het oneens bent met de uitspraak, of als je de uitspraak grotendeels onwaar vindt.</li>
      <li class="collection-item">Klik <strong>N</strong> aan als je neutraal bent, niet kunt beslissen, of als je de uitspraak ongeveer even waar als onwaar vindt.</li>
      <li class="collection-item">Klik <strong>E</strong> aan als je het eens bent met de uitspraak, of als je de uitspraak grotendeels waar vindt.</li>
      <li class="collection-item">Klik <strong>HE</strong> aan als je het helemaal eens bent met de uitspraak, of als je de uitspraak absoluut waar vindt.</li>
    </ul>'
  },
  create_question(:v1, 'Ik ben geen tobber.', false),
  create_question(:v2, 'Ik vind de meeste mensen die ik ontmoet echt aardig.', false),
  create_question(:v3, 'Ik heb een heel levendige fantasie.', false),
  create_question(:v4, 'Ik ben vaak cynisch en sceptisch over de bedoelingen van anderen.', false),
  create_question(:v5, 'Ik sta bekend om mijn gezond verstand.', false),
  create_question(:v6, 'Ik word vaak kwaad om de manier waarop mensen me behandelen.', false),
  create_question(:v7, 'Ik ga mensenmenigtes uit de weg.', false),
  create_question(:v8, 'Ik ben niet erg geïnteresseerd in kunst.', false),
  create_question(:v9, 'Ik ben niet sluw of geslepen.', false),
  create_question(:v10, 'Ik stoor mij niet aan een beetje rommel in mijn kamer.', false),
  create_question(:v11, 'Ik voel me zelden eenzaam of triest.', false),
  create_question(:v12, 'Ik ben dominant, krachtig en zelfverzekerd.', false),
  create_question(:v13, 'Zonder sterke emoties zou ik het leven niet interessant vinden.', false),
  create_question(:v14, 'Sommige mensen vinden mij zelfzuchtig en egoïstisch.', false),
  create_question(:v15, 'Ik probeer alle aan mij opgedragen taken gewetensvol uit te voeren.', false),
  create_question(:v16, 'In gezelschap maak ik me zorgen dat ik een gek figuur sla.', false),
  create_question(:v17, 'Mijn stijl in werk en spel is kalm en ongehaast.', false),
  create_question(:v18, 'Ik heb tamelijk vaste gewoonten.', false),
  create_question(:v19, 'Ik werk liever met anderen samen dan met ze te wedijveren.', false),
  create_question(:v20, 'Ik ben niet erg ambitieus.', false),
  create_question(:v21, 'Ik ga me zelden aan iets te buiten.', false),
  create_question(:v22, 'Ik verlang vaak sterk naar opwinding.', false),
  create_question(:v23, 'Ik heb vaak plezier in het spelen met theorieën of abstracte ideeën.', false),
  create_question(:v24, 'Ik mag graag een beetje opscheppen over mijn talenten en prestaties.', false),
  create_question(:v25, 'Ik kan mijzelf vrij goed oppeppen om dingen op tijd af te krijgen.', false),
  create_question(:v26, 'Ik voel me vaak hulpeloos en wil dan graag dat iemand anders mijn problemen oplost.', false),
  create_question(:v27, 'Ik ben nog nooit uitzinnig van vreugde geweest. ', false),
  create_question(:v28, 'Ik vind dat leerlingen alleen maar in verwarring worden gebracht door ze te laten luisteren naar sprekers met afwijkende ideeën.', false),
  create_question(:v29, 'Ik vind dat men bij het maken van wetten en sociaal beleid moet denken aan degenen die geraakt kunnen worden. ', false),
  create_question(:v30, 'Door de jaren heen heb ik een aantal behoorlijk stomme dingen gedaan.', false),
  create_question(:v31, 'Ik ben gauw ergens bang voor.', false),
  create_question(:v32, 'Ik vind het niet erg leuk om zomaar een praatje met iemand te maken.', false),
  create_question(:v33, 'Ik probeer al mijn gedachten steeds op de realiteit gericht te houden en vermijd dagdromerijen.', false),
  create_question(:v34, 'Ik geloof dat de meeste mensen in wezen van goede wil zijn.', false),
  create_question(:v35, 'Ik heb de meeste zaken in mijn leven vrij goed onder controle.', false),
  create_question(:v36, 'Ik ben een gelijkmatig mens.', false),
  create_question(:v37, 'Ik houd er van veel mensen om me heen te hebben.', false),
  create_question(:v38, 'Soms ben ik geheel verdiept in de muziek waar ik naar luister.', false),
  create_question(:v39, 'Als het nodig is ben ik bereid om mensen te manipuleren om te krijgen wat ik wil.', false),
  create_question(:v40, 'Ik houd mijn spullen netjes en schoon.', false),
  create_question(:v41, 'Soms voel ik me volkomen waardeloos.', false),
  create_question(:v42, 'Vaak kom ik niet op voor mijn rechten zoals ik zou moeten doen.', false),
  create_question(:v43, 'Ik voel zelden sterke emoties.', false),
  create_question(:v44, 'Ik probeer hoffelijk te zijn tegen iedereen die ik ontmoet.', false),
  create_question(:v45, 'Soms ben ik niet zo betrouwbaar als ik zou moeten zijn.', false),
  create_question(:v46, 'Ik voel me zelden verlegen in gezelschap.', false),
  create_question(:v47, 'Mijn manier van doen is energiek en krachtig.', false),
  create_question(:v48, 'Ik vind het interessant om met nieuwe hobby´s te beginnen.', false),
  create_question(:v49, 'Ik kan sarcastisch en scherp zijn als het moet.', false),
  create_question(:v50, 'Ik heb duidelijke doelen voor ogen en werk daar op een systematische manier naar toe.', false),
  create_question(:v51, 'Het kost mij moeite mijn verlangens te weerstaan.', false),
  create_question(:v52, 'Ik hoef op vakantie niet zo nodig spannende dingen te doen.', false),
  create_question(:v53, 'Ik vind filosofische discussies saai.', false),
  create_question(:v54, 'Ik praat niet graag over mijzelf en mijn prestaties.', false),
  create_question(:v55, 'Ik verknoei veel tijd voordat ik echt aan het werk ga.', false),
  create_question(:v56, 'Ik vind dat ik in staat ben de meeste van mijn problemen zelf op te lossen.', false),
  create_question(:v57, 'Ik heb mij wel eens overweldigend gelukkig gevoeld. ', false),
  create_question(:v58, 'Ik vind dat wetgeving en sociaal beleid steeds moeten worden aangepast aan veranderingen in de wereld.', false),
  create_question(:v59, 'Ik ben niet erg begaan met de daklozen.', false),
  create_question(:v60, 'Ik doordenk de dingen goed voor ik een beslissing neem.', false),
  create_question(:v61, 'Ik voel me zelden angstig of zorgelijk.', false),
  create_question(:v62, 'Ik sta bekend als een warm en vriendelijk mens.', false),
  create_question(:v63, 'Ik heb een actief fantasieleven.', false),
  create_question(:v64, 'Ik denk dat de meeste mensen je zullen gebruiken als je ze de kans geeft.', false),
  create_question(:v65, 'Ik houd mezelf goed op de hoogte en neem doorgaans verstandige beslissingen.', false),
  create_question(:v66, 'Ik sta bekend als opvliegend en lichtgeraakt.', false),
  create_question(:v67, 'Ik geef er meestal de voorkeur aan om dingen alleen te doen.', false),
  create_question(:v68, 'Kijken naar ballet of moderne dans verveelt me.', false),
  create_question(:v69, 'Ik kan niemand bedriegen, zelfs als ik het zou willen.', false),
  create_question(:v70, 'Ik ben niet erg systematisch.', false),
  create_question(:v71, 'Ik ben zelden verdrietig of depressief.', false),
  create_question(:v72, 'Ik heb vaak de leiding gehad in groepen waar ik bij hoorde.', false),
  create_question(:v73, 'Mijn gevoel over dingen is belangrijk voor mij.', false),
  create_question(:v74, 'Sommige mensen vinden mij koel en berekenend.', false),
  create_question(:v75, 'Ik betaal mijn schulden altijd direct en volledig.', false),
  create_question(:v76, 'Soms schaam ik me zo dat ik wel door de grond wil zakken.', false),
  create_question(:v77, 'Mijn werkwijze is meestal traag maar gestadig.', false),
  create_question(:v78, 'Ik hecht aan oude methoden waarmee ik vertrouwd ben.', false),
  create_question(:v79, 'Ik laat mijn boosheid niet gauw blijken, ook al is die terecht.', false),
  create_question(:v80, 'Als ik begin met een plan om iets aan mezelf te veranderen, of voor mezelf iets te leren, dan verwatert dat meestal vrij gauw weer bij mij.', false),
  create_question(:v81, 'Het kost me geen moeite verleidingen te weerstaan.', false),
  create_question(:v82, " Ik heb wel eens dingen alleen maar voor de `kick'of de sensatie gedaan.", false),
  create_question(:v83, 'Ik houd er van problemen of puzzels op te lossen.', false),
  create_question(:v84, 'Ik ben beter dan de meeste mensen, en dat weet ik ook.', false),
  create_question(:v85, 'Ik ben een productief mens die een klus altijd voor elkaar krijgt.', false),
  create_question(:v86, 'Wanneer ik onder grote spanning sta, heb ik soms het gevoel dat ik er onderdoor ga.', false),
  create_question(:v87, 'Ik ben geen vrolijke optimist.', false),
  create_question(:v88, 'Ik vind dat we beslissingen in morele zaken van onze religieuze leiders mogen verwachten.', false),
  create_question(:v89, 'We kunnen nooit te veel doen voor de armen en bejaarden.', false),
  create_question(:v90, 'Af en toe doe ik eerst iets en denk er later pas over na.', false),
  create_question(:v91, 'Ik voel me vaak gespannen en zenuwachtig.', false),
  create_question(:v92, 'Veel mensen vinden mij enigszins koel en afstandelijk.', false),
  create_question(:v93, 'Ik houd er niet van mijn tijd te verdoen met dagdromen.', false),
  create_question(:v94, 'De meeste mensen waar ik mee te maken heb zijn eerlijk en te vertrouwen.', false),
  create_question(:v95, 'Ik kom vaak in situaties terecht waar ik niet goed op voorbereid ben.', false),
  create_question(:v96, 'Ik word niet gezien als een lichtgeraakt of humeurig iemand.', false),
  create_question(:v97, 'Ik heb echt behoefte aan gezelschap als ik lange tijd alleen ben.', false),
  create_question(:v98, 'Ik ben geïntrigeerd door de patronen die ik vind in de kunst en de natuur.', false),
  create_question(:v99, 'Met volslagen eerlijkheid kom je niet ver in het zaken doen.', false),
  create_question(:v100, 'Ik bewaar alles liefst op een vaste plaats zodat ik precies weet waar het is.', false),
  create_question(:v101, 'Ik heb me wel eens diep schuldig of zondig gevoeld.', false),
  create_question(:v102, 'Tijdens bijeenkomsten laat ik anderen vaak het woord doen.', false),
  create_question(:v103, 'Ik schenk zelden veel aandacht aan mijn gevoelens van het moment.', false),
  create_question(:v104, 'Over het algemeen probeer ik attent en zorgzaam te zijn.', false),
  create_question(:v105, 'Ik speel wel eens vals bij een spelletje kaart.', false),
  create_question(:v106, 'Ik word niet erg verlegen wanneer mensen de spot met me drijven en me plagen.', false),
  create_question(:v107, 'Ik voel me vaak alsof ik barst van energie.', false),
  create_question(:v108, 'Ik probeer vaak nieuwe en buitenlandse gerechten.', false),
  create_question(:v109, 'Als ik mensen niet mag, laat ik dat ook merken.', false),
  create_question(:v110, 'Ik werk hard om mijn doelen te bereiken.', false),
  create_question(:v111, 'Wanneer ik mijn lievelingseten voorgeschoteld krijg, eet ik vaak te veel.', false),
  create_question(:v112, 'Ik vermijd meestal films die schokkend of eng zijn.', false),
  create_question(:v113, 'Ik verlies soms mijn belangstelling als mensen over heel abstracte, theoretische zaken praten.', false),
  create_question(:v114, 'Ik ben geen opschepper.', false),
  create_question(:v115, 'Ik kan mezelf er moeilijk toe brengen om te doen wat ik moet doen.', false),
  create_question(:v116, 'Ik houd het hoofd koel in crisissituaties.', false),
  create_question(:v117, 'Soms loop ik over van geluk.', false),
  create_question(:v118, 'De ideeën over goed en kwaad van mensen in andere culturen verdienen respect, ook als ze sterk van de onze verschillen.', false),
  create_question(:v119, 'Ik heb geen sympathie voor bedelaars.', false),
  create_question(:v120, 'Ik houd altijd rekening met de gevolgen voor ik iets onderneem.', false),
  create_question(:v121, 'Ik voel mij zelden zenuwachtig.', false),
  create_question(:v122, 'Ik vind het echt leuk om met mensen te praten.', false),
  create_question(:v123, 'Ik kan mij met plezier helemaal verliezen in een dagdroom of fantasie.', false),
  create_question(:v124, 'Als iemand iets aardigs voor mij doet, ben ik achterdochtig.', false),
  create_question(:v125, 'Ik heb een goed oordeelsvermogen.', false),
  create_question(:v126, 'Ik walg vaak van mensen waar ik mee te maken krijg.', false),
  create_question(:v127, 'Ik geef de voorkeur aan werk dat ik alleen kan doen zonder gestoord te worden door anderen.', false),
  create_question(:v128, 'Poëzie doet mij weinig tot niets.', false),
  create_question(:v129, 'Ik zou het vreselijk vinden om schijnheilig gevonden te worden.', false),
  create_question(:v130, 'Het lijkt mij maar niet te lukken om de dingen goed op orde te hebben.', false),
  create_question(:v131, 'Ik ben geneigd het mijzelf te verwijten als er iets fout gaat.', false),
  create_question(:v132, 'Anderen kijken vaak naar mij als er een beslissing genomen moet worden.', false),
  create_question(:v133, 'Ik ken een breed scala van emoties en gevoelens.', false),
  create_question(:v134, 'Ik sta niet bekend om mijn vrijgevigheid.', false),
  create_question(:v135, 'Als ik iets beloof, kan men er op rekenen dat ik die belofte nakom.', false),
  create_question(:v136, 'Ik heb dikwijls het gevoel dat ik niet zo goed ben als anderen. ', false),
  create_question(:v137, 'Ik ben niet zo snel en levendig als anderen.', false),
  create_question(:v138, 'Ik breng mijn tijd het liefst door in een vertrouwde omgeving.', false),
  create_question(:v139, 'Wanneer ik ben beledigd, probeer ik het maar te vergeven en vergeten.', false),
  create_question(:v140, 'Ik ben niet zo gedreven om hogerop te komen.', false),
  create_question(:v141, 'Ik geef zelden toe aan mijn impulsen.', false),
  create_question(:v142, 'Ik ben graag daar waar wat te beleven valt.', false),
  create_question(:v143, 'Ik geniet van het bezig zijn met ingewikkelde puzzels.', false),
  create_question(:v144, 'Ik heb een zeer hoge dunk van mijzelf.', false),
  create_question(:v145, 'Als ik aan een project begin, maak ik het bijna altijd af.', false),
  create_question(:v146, 'Ik vind het vaak moeilijk tot een besluit te komen.', false),
  create_question(:v147, 'Ik zie mezelf niet echt als een vrolijk en opgewekt persoon.', false),
  create_question(:v148, 'Ik geloof dat het beter is om vast te houden aan je eigen overtuiging dan open te blijven staan voor allerlei andere meningen.', false),
  create_question(:v149, 'Ik vind menselijke behoeften belangrijker dan economische waarden.', false),
  create_question(:v150, 'Ik doe dingen vaak in een opwelling.', false),
  create_question(:v151, 'Ik maak me vaak zorgen over dingen die mis zouden kunnen gaan.', false),
  create_question(:v152, 'Ik vind het gemakkelijk om vlot en plezierig met vreemden om te gaan.', false),
  create_question(:v153, 'Als ik merk dat ik zit te dagdromen, dan breek ik dat af en richt ik me op de een of andere activiteit.', false),
  create_question(:v154, 'Mijn eerste reactie is om mensen te vertrouwen.', false),
  create_question(:v155, 'Ik lijk nergens helemaal succesvol in te zijn.', false),
  create_question(:v156, 'Er moet heel wat gebeuren voor ik kwaad word.', false),
  create_question(:v157, 'Ik zit met vakantie liever op een druk strand dan in een afgelegen hut in het bos.', false),
  create_question(:v158, 'Sommige soorten muziek fascineren mij mateloos.', false),
  create_question(:v159, 'Soms zorg ik er door misleiding voor dat mensen doen wat ik wil.', false),
  create_question(:v160, 'Ik ben geneigd nogal nauwgezet en veeleisend te zijn.', false),
  create_question(:v161, 'Ik heb een lage dunk van mijzelf.', false),
  create_question(:v162, 'Ik ga liever mijn eigen gang dan dat ik leiding geef aan anderen.', false),
  create_question(:v163, 'Ik merk zelden de stemmingen of gevoelens op, die verschillende omgevingen oproepen.', false),
  create_question(:v164, 'De meeste mensen die ik ken, mogen mij graag.', false),
  create_question(:v165, 'Ik houd strikt vast aan mijn ethische principes.', false),
  create_question(:v166, "Ik voel me op m'n gemak in het bijzijn van mijn meerderen of andere autoriteiten.", false),
  create_question(:v167, 'Het lijkt alsof ik altijd haast heb.', false),
  create_question(:v168, 'Ik vind dat vaak iets nieuws proberen het leven interessant maakt.', false),
  create_question(:v169, 'Als iemand strijd met mij zoekt, sta ik klaar om terug te vechten.', false),
  create_question(:v170, 'Ik streef ernaar alles wat in mijn mogelijkheden ligt te bereiken.', false),
  create_question(:v171, 'Ik eet mezelf wel eens misselijk.', false),
  create_question(:v172, 'Ik houd van de opwinding van de achtbaan.', false),
  create_question(:v173, 'Ik ben niet erg geïnteresseerd in het speculeren over het wezen van het universum of van de mens.', false),
  create_question(:v174, 'Ik vind dat ik niet beter ben dan anderen, ongeacht hoe ze er voor staan.', false),
  create_question(:v175, 'Wanneer een project te moeilijk wordt, ben ik geneigd met iets anders te beginnen.', false),
  create_question(:v176, 'Ik heb mezelf tamelijk goed in de hand in een crisis.', false),
  create_question(:v177, 'Ik ben een vrolijk en levendig iemand.', false),
  create_question(:v178, 'Ik vind mijzelf ruimdenkend en tolerant jegens mensen met een andere levensstijl.', false),
  create_question(:v179, 'Ik vind dat elk mens het waard is gerespecteerd te worden.', false),
  create_question(:v180, 'Ik neem zelden overhaaste beslissingen.', false),
  create_question(:v181, 'Ik heb minder angsten dan de meeste mensen.', false),
  create_question(:v182, 'Ik heb sterke emotionele banden met mijn vrienden.', false),
  create_question(:v183, 'Als kind vond ik fantasiespelletjes zelden leuk.', false),
  create_question(:v184, 'Ik denk meestal het beste van mensen.', false),
  create_question(:v185, 'Ik heb veel bekwaamheden.', false),
  create_question(:v186, 'Ik heb mij wel eens verbitterd en vervuld van wrok gevoeld.', false),
  create_question(:v187, 'Feesten en partijtjes vind ik doorgaans vervelend.', false),
  create_question(:v188, 'Wanneer ik een gedicht lees of naar een kunstwerk kijk, voel ik soms een koude rilling of een golf van opwinding.', false),
  create_question(:v189, 'Soms dreig ik mensen of vlei ik ze, zodat ze doen wat ik wil.', false),
  create_question(:v190, 'Wat schoonmaken betreft ben ik niet dwangmatig.', false),
  create_question(:v191, 'Soms komt alles mij nogal somber en hopeloos voor.', false),
  create_question(:v192, 'In conversaties ben ik doorgaans het meest aan het woord.', false),
  create_question(:v193, 'Ik vind het gemakkelijk om mij in anderen in te leven - zelf te voelen wat zij ervaren.', false),
  create_question(:v194, 'Ik beschouw mijzelf als iemand die veel voor de medemens over heeft.', false),
  create_question(:v195, 'Ik probeer taken zorgvuldig te doen, zodat ze niet nog eens overgedaan hoeven te worden.', false),
  create_question(:v196, 'Wanneer ik iemand iets verkeerds heb gezegd of aangedaan, dan durf ik die nauwelijks weer onder ogen te komen.', false),
  create_question(:v197, 'Ik heb een jachtig leven.', false),
  create_question(:v198, 'Op vakanties ga ik het liefst naar een oud en vertrouwd plekje terug.', false),
  create_question(:v199, 'Ik ben koppig en onverzettelijk.', false),
  create_question(:v200, 'Ik streef er naar uit te blinken in alles wat ik doe.', false),
  create_question(:v201, 'Soms doe ik in een opwelling dingen waar ik later spijt van heb.', false),
  create_question(:v202, 'Ik houd van felle kleuren en opvallende kleding.', false),
  create_question(:v203, 'Ik ben erg leergierig.', false),
  create_question(:v204, 'Ik prijs liever anderen dan zelf geprezen te worden.', false),
  create_question(:v205, 'Er zijn zoveel kleine dingen die gedaan moeten worden, dat ik het soms allemaal gewoon niet wil weten.', false),
  create_question(:v206, 'Wanneer alles fout lijkt te gaan,  kan ik toch nog goede beslissingen nemen.', false),
  create_question(:v207, 'Om mijn ervaringen te beschrijven gebruik ik zelden woorden als `fantastisch!´ of `sensationeel!´ .', false),
  create_question(:v208, 'Als mensen tegen hun 25ste nog niet weten waar ze in geloven is er volgens mij iets mis met ze.', false),
  create_question(:v209, 'Ik voel sympathie voor mensen die een slechter lot hebben getroffen dan ik.', false),
  create_question(:v210, 'Als ik op reis ga, maak ik tevoren een zorgvuldig plan.', false),
  create_question(:v211, 'Soms komen er angstaanjagende gedachten bij mij op.', false),
  create_question(:v212, 'Ik ben persoonlijk geïnteresseerd in de mensen met wie ik werk.', false),
  create_question(:v213, 'Ik zou het moeilijk vinden om mijn gedachten zomaar te laten dwalen.', false),
  create_question(:v214, 'Ik heb behoorlijk veel vertrouwen in de menselijke natuur.', false),
  create_question(:v215, 'Ik ben efficiënt en doelmatig in mijn werk.', false),
  create_question(:v216, 'Zelfs kleine ergernissen kunnen mij frustreren.', false),
  create_question(:v217, 'Ik houd van feesten met veel mensen.', false),
  create_question(:v218, 'Ik vind gedichten die gevoelens en beelden oproepen fijner om te lezen dan verhalende gedichten.', false),
  create_question(:v219, 'Ik ben wel trots op mijn handigheid in het bespelen van mensen.', false),
  create_question(:v220, 'Ik besteed veel tijd aan het zoeken naar dingen die ik niet goed heb opgeborgen.', false),
  create_question(:v221, 'Wanneer dingen mis gaan, raak ik maar al te vaak ontmoedigd en heb ik zin om het op te geven.', false),
  create_question(:v222, 'Ik vind het niet gemakkelijk om de leiding op me te nemen.', false),
  create_question(:v223, 'Vreemde dingen - zoals bepaalde geuren of de namen van verre oorden - kunnen hevige stemmingen in mij oproepen.', false),
  create_question(:v224, 'Ik doe alles om anderen te helpen waar ik kan.', false),
  create_question(:v225, 'Ik probeer naar mijn werk of school te gaan, ook wanneer ik mij niet goed voel.', false),
  create_question(:v226, 'Ik voel mij onbeholpen in het bijzijn van anderen.', false),
  create_question(:v227, 'Ik ben een heel actief persoon.', false),
  create_question(:v228, 'Ik volg altijd dezelfde route als ik ergens heen ga.', false),
  create_question(:v229, 'Ik verzeil vaak in meningsverschillen met mijn familie en collega\'s.', false),
  create_question(:v230, 'Ik heb wel iets van een `workaholic´.', false),
  create_question(:v231, 'Ik ben altijd in staat mijn gevoelens te beheersen.', false),
  create_question(:v232, 'Ik maak graag deel uit van de menigte bij sportevenementen.', false),
  create_question(:v233, 'Ik heb een breed scala aan intellectuele interesses.', false),
  create_question(:v234, 'Ik ben een beter mens dan de meesten.', false),
  create_question(:v235, 'Ik heb veel zelfdiscipline.', false),
  create_question(:v236, 'Ik ben emotioneel behoorlijk stabiel.', false),
  create_question(:v237, 'Ik lach gemakkelijk.', false),
  create_question(:v238, 'Ik vind dat mensen de traditionele waarden moeten eren in plaats van ze ter discussie te stellen. ', false),
  create_question(:v239, 'Ik ben mild in mijn oordeel over anderen.', false),
  create_question(:v240, 'Ik denk eerst goed na voordat ik een vraag beantwoord.', false)
]

questionnaire.content = { questionnaire: content, scores: [] }
questionnaire.title = title
questionnaire.save!
