apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-one-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-one-am
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-one-am
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-one-am
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_one_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-two-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-two-am
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-two-am
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-two-am
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_two_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-three-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-three-am
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-three-am
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-three-am
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_three_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-four-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-four-am
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-four-am
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-daily-at-four-am
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_four_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-daily
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-daily
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-daily
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-hourly
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-hourly
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-hourly
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-hourly
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/hourly']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-thirty-minutely
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-thirty-minutely
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-thirty-minutely
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-thirty-minutely
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/thirty_minutely']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-five-minutely
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-five-minutely
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-five-minutely
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-five-minutely
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/five_minutely']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-minutely
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app: svc-questionnaires-scheduler
    observability.researchable.nl/job: svc-questionnaire-scheduler-minutely
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: svc-questionnaires-scheduler
        observability.researchable.nl/job: svc-questionnaire-scheduler-minutely
    spec:
      template:
        metadata:
          labels:
            app: svc-questionnaires-scheduler
            observability.researchable.nl/job: svc-questionnaire-scheduler-minutely
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/minutely']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
