apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-one-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_one_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-two-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_two_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-three-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_three_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily-at-four-am
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily_at_four_am']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-daily
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/daily']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-hourly
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/hourly']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-thirty-minutely
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/thirty_minutely']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-five-minutely
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/five_minutely']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: svc-questionnaire-scheduler-minutely
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Replace
          restartPolicy: Never
          imagePullSecrets:
            - name: gitlab-auth
          containers:
          - name: cron-container
            image: registry.gitlab.com/researchable/general/docker-images/curl:latest
            imagePullPolicy: IfNotPresent
            args: ['-X', 'POST', 'http://$(API_KEY):$(API_SECRET)@svc-questionnaires-service:3000/api/v1/basic_auth_api/scheduling/minutely']
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-questionnaires-secret
                  key: __CI_COMMIT_REF_NAME___API_SECRET

