apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sportdatavalley-svc-questionnaires-tls
  namespace: sdv-mvp-develop
spec:
  secretName: sportdatavalley-svc-questionnaires-tls
  dnsNames:
  - svc-questionnaires.app.sportdatavalley.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: svc-questionnaires
  namespace: sdv-mvp-develop
  labels:
    app: svc-questionnaires
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - svc-questionnaires.app.sportdatavalley.dev
    secretName: sportdatavalley-svc-questionnaires-tls
  rules:
  - host: svc-questionnaires.app.sportdatavalley.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-questionnaires-service
          servicePort: 3000
