apiVersion: v1
kind: Service
metadata:
  name: svc-questionnaires-service
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
  labels:
    app.kubernetes.io/name: svc-questionnaires
    app.kubernetes.io/component: web
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: svc-questionnaires
    app.kubernetes.io/component: web
