apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-questionnaires-worker
  namespace: sdv-mvp-__CI_COMMIT_DOWN_REF_NAME__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-questionnaires-worker
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50 