# Beware! This file is public by definition
default: &default
  project_start_date: '2019-04-07'
  project_end_date: '2019-05-16'
  default_team_name: 'Evaluatieonderzoek'
  logo:
    mentor_logo: 'U_can_act_logo_CMYK_BLAUW.png'
    student_logo: 'U_can_act_logo_CMYK_GROEN.png'
    fallback_logo: 'U_can_act_logo_ZWART.png'
    company_logo: 'rug_logo.png'
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
