default: &defaults
  push_api_key: "a0c0b397-a5cb-46e6-b380-780e905cfe2f"
  name: <%= ENV["PROJECT_NAME"] %>

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
  log_path: '/tmp'

staging:
  <<: *defaults
  active: true
  log_path: '/tmp'
